version: '3'
services:
  simiscore-biblio:
    image: evidence-simiscore-biblio
    build:   # build using Dockfile in this directory
      context: .
      dockerfile: Dockerfile
    environment:
      # Fastapi/gunicorn settings, see 
      # https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#environment-variables
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
      - "TIMEOUT=180"
      # - "GRACEFUL_TIMEOUT=180"
    ports:
      - "${API_PORT}:80"
